### ISSUE TITLE
Crash on Create World if default World Type settings exist in config

### ISSUE THREAD

**Issue by RiverC** [coolsquid/MiscTweaks#5]
Further testing reveals it to be not chunkprovider settings but

    # Sets a default (initially selected) world type. Leave empty to disable. [default: ]
    S:defaultWorldType=4

Here is the result when clicking the button for Create World

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  NoCubesLoadingPlugin (NoCubes-1.12.2-0.3.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.151.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.2.1-build.0377.jar)
  Quark Plugin (Quark-r1.5-167.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar)
  MiscTweaksPlugin (MiscTweaks-1.12.2-1.5.0.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/9/19 9:40 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at coolsquid.misctweaks.util.OptionTweaks$Listener.onGuiInit(OptionTweaks.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_965_Listener_onGuiInit_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:480)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraft.client.gui.GuiWorldSelection.func_146284_a(SourceFile:85)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:116)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by coolsquid** [comment]
The `defaultWorldType` option accepts the world type's name, not its index (this was changed when I overhauled the world setup options). In Vanilla, the world types are `default`, `flat`, `largeBiomes`, `amplified` and `customized`.

I'll add a note about this to the option comment.

**Comment by RiverC** [comment]
Thanks a lot!
